SuperShraga/Models/ShoppingCart.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using SuperShraga.Controllers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace SuperShraga.Models
{
    public class ShoppingCart
    {
        string ShoppingCartId { get; set; }

        public static ShoppingCart GetCart(string userId)
        {
            var cart = new ShoppingCart();
            cart.ShoppingCartId = userId;
            return cart;
        }

        public void AddToCart(Item item, ApplicationDbContext context)
        {

            var cartItem = context.Carts.SingleOrDefault(
                c => c.UserId == ShoppingCartId
                && c.ItemId == item.Id);

            if (cartItem == null)
            {

                cartItem = new Cart
                {
                    ItemId = item.Id,
                    UserId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                    
                };
                context.Carts.Add(cartItem);
            }
            else
            {

                cartItem.Count++;
            }

            context.SaveChanges();
        }
        public int RemoveFromCart(int id, ApplicationDbContext context)
        {

            var cartItem = context.Carts.Single(
                cart => cart.UserId == ShoppingCartId
                && cart.RecordId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    context.Carts.Remove(cartItem);
                }

                context.SaveChanges();
            }
            return itemCount;
        }

        public void EmptyCart(ApplicationDbContext context)
        {
            var cartItems = context.Carts.Where(
                cart => cart.UserId == ShoppingCartId);

            foreach (var cartItem in cartItems)
            {
                context.Carts.Remove(cartItem);
            }

            context.SaveChanges();
        }
        public List<Cart> GetCartItems(ApplicationDbContext context)
        {
            List<Cart> cartItems = context.Carts.Where(
                cart => cart.UserId == ShoppingCartId).ToList();

            foreach (var cartItem in cartItems)
            {
                cartItem.Item = context.Items.SingleOrDefault(i => i.Id == cartItem.ItemId);
            }

            return cartItems;
        }
        public int GetCount(ApplicationDbContext context)
        {
            List<Cart> cartList = GetCartItems(context);
            int? count = 0;
            foreach (Cart c in cartList)
            {
                count += c.Count;
            }

            return count ?? 0;
        }

        public decimal GetTotal(ApplicationDbContext context)
        {
            List<Cart> cartList = GetCartItems(context);
            decimal? total = 0;
            foreach (Cart c in cartList)
            {
                total += c.Item.Price * c.Count;
            }

            return total ?? decimal.Zero;
        }

        public Order CreateOrder(Order order, bool promo, ApplicationDbContext context)
        {
            decimal orderTotal = 0;
            decimal orderPromo = 1;

            if (promo)
                orderPromo = 2;

            var cartItems = GetCartItems(context);

            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ItemId = item.ItemId,
                    OrderId = order.OrderId,
                    UnitPrice = item.Item.Price,
                    Quantity = item.Count
                };

                orderTotal += (item.Count * item.Item.Price);
                orderTotal /= orderPromo;

                context.OrderDetails.Add(orderDetail);

            }

            order.Total = orderTotal;

            context.SaveChanges();

            EmptyCart(context);

            return order;
        }
    }
}

SuperShraga/Models/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperShraga.Models
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
        public int CartCount { get; set; }
    }
}

SuperShraga/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SuperShraga.Models;
using SuperShraga.Models.Identity;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SuperShraga.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;

        const string PromoCode = "50";

        public CheckoutController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult AddressAndPayment()
        {
            string userId = _userManager.GetUserId(HttpContext.User);
            var cart = ShoppingCart.GetCart(userId);

            if (cart.GetCount(_context) == 0)
            {
                return View("Error");
            }
            else
                return View();
        }

        [HttpPost]
        public IActionResult AddressAndPayment(IFormCollection values)
        {
            var order = new Order();
            string userId = _userManager.GetUserId(HttpContext.User);
            var cart = ShoppingCart.GetCart(userId);

            if (cart.GetCount(_context) == 0)
            {
                return View("Error");
            }
            if (ModelState.IsValid)
            {
                bool promo = false;
                if(string.Equals(values["PromoCode"], PromoCode))
                {
                    promo = true;
                }

                order.UserId = userId;
                order.OrderDate = DateTime.Now;

                order.Address = values["Address"];
                order.City = values["City"];
                order.Country = values["Country"];
                order.Email = values["Email"];
                order.LastName = values["LastName"];
                order.FirstName = values["FirstName"];

                _context.Orders.Add(order);
                _context.SaveChanges();

                order = cart.CreateOrder(order, promo, _context);

                _context.Orders.Update(order);

                return RedirectToAction("complete",
                    new { id = order.OrderId, userId = order.UserId });
            }

            return View(order);
        }

        public IActionResult Complete(int id, string userId)
        {

            bool isValid = _context.Orders.Any(
                o => o.OrderId == id &&
                o.UserId == userId);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

SuperShraga/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SuperShraga.Models;
using SuperShraga.Models.Identity;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SuperShraga.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;
        string _userid;


        public ShoppingCartController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            string userid = _userManager.GetUserId(HttpContext.User);
            var cart = ShoppingCart.GetCart(userid);


            ShoppingCartViewModel viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(_context),
                CartTotal = cart.GetTotal(_context),
                CartCount = cart.GetCount(_context)
            };

            return View(viewModel);
        }

        public IActionResult AddToCart(int id)
        {

            var addedItem = _context.Items
                .Single(item => item.Id == id);


            string userid = _userManager.GetUserId(HttpContext.User);
            var cart = ShoppingCart.GetCart(userid);
            cart.AddToCart(addedItem, _context);


            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int id)
        {

            string userid = _userManager.GetUserId(HttpContext.User);
            var cart = ShoppingCart.GetCart(userid);

            List<Cart> cartsList = cart.GetCartItems(_context);

            string itemName = cartsList.SingleOrDefault(item => item.RecordId == id).Item.Name;

            int itemCount = cart.RemoveFromCart(id,_context);


            var results = new ShoppingCartRemoveViewModel
            {
                Message = itemName +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(_context),
                CartCount = cart.GetCount(_context),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
            //return RedirectToAction("Index");

        }

        public IActionResult CartSummary()
        {
            string userid = _userManager.GetUserId(HttpContext.User);
            var cart = ShoppingCart.GetCart(userid);

            ViewData["CartCount"] = cart.GetCount(_context);
            return PartialView("CartSummary");
        }

        public IActionResult EmptyCart()
        {
            string userid = _userManager.GetUserId(HttpContext.User);
            var cart = ShoppingCart.GetCart(userid);
            cart.EmptyCart(_context);
            return RedirectToAction("Index");
        }
    }
}

SuperShraga/Views/ShoppingCart/CartSummary.cshtml
@*@model IEnumerable<SuperShraga.Models.ShoppingCart>

    @{
        ViewData["Title"] = "CartSummary";
    }

    <h2>CartSummary</h2>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
    }
        </tbody>
    </table>*@

@Html.ActionLink("Cart(" + ViewData["CartCount"] + ")",
"Index",
"ShoppingCart",
new { id = "cart-status" })

SuperShraga/Views/ShoppingCart/Index.cshtml
@model SuperShraga.Models.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}
<script src="~/lib/jquery/dist/jquery.min.js">
    type = "text/javascript" >
</script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", {"id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.itemCount == 0) {
                            $('#row-' + data.deleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.deleteId).text(data.itemCount);
                        }
                        $('#cart-total').text(data.cartTotal);
                        $('#cart-count').text(data.cartCount);
                        $('#update-message').text(data.message);
                        $('#cart-status').text('Cart (' + data.cartCount + ')');
                    });
            }
        });
    });
</script>
<h3>
    <em>Review</em> your cart:
</h3>
<p class="button">
    @Html.ActionLink("Checkout>> ", "AddressAndPayment", "Checkout")
</p>
<div id="update-message">
</div>
<table>
    <tr>
        <th>
            Item Name
        </th>
        <th>
            Price (each)
        </th>
        <th>
            Quantity
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.CartItems)
    {
        <tr id="row-@item.RecordId">
            <td>
                @Html.ActionLink(item.Item.Name,
"Details", "Store", new { id = item.ItemId }, null)
            </td>
            <td>
                @item.Item.Price
            </td>
            <td id="item-count-@item.RecordId">
                @item.Count
            </td>
            <td>
                <a href="#" class="RemoveLink"
                   data-id="@item.RecordId">
                    Remove
                    from cart
                </a>
            </td>
        </tr>
    }
        <tr>
            <td>
                Total
            </td>
            <td id="cart-total">
                @Model.CartTotal
            </td>
            <td id="cart-count">
               @Model.CartCount
            </td>
            <td>
                @Html.ActionLink("Empty Cart ", "EmptyCart", "ShoppingCart")
            </td>
        </tr>
</table>