SuperShraga/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuperShraga.Models;
using SuperShraga.Models.Identity;

namespace SuperShraga.Controllers
{
    public class BranchesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<ApplicationUser> _userManager;


        public BranchesController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Branches
        public async Task<IActionResult> Index()
        {
            //var branches = new List<Branch>()
            //{
            //    new Branch()
            //    {
            //        Address = "Address1",
            //        Longitude = -118.259653f,
            //        Latitude = 34.046438f
            //    },
            //    new Branch()
            //    {
            //        Address = "Address2",
            //        Longitude = -117.259653f,
            //        Latitude = 34.046438f
            //    },
            //    new Branch()
            //    {
            //        Address = "Address3",
            //        Longitude = -117.259653f,
            //        Latitude = 35.046438f
            //    }
            //};

            //return View(branches);

            return View(await _context.Branches.ToListAsync());
        }

        // GET: Branches/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .SingleOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // GET: Branches/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Address,OpenHours,Latitude,Longitude")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                _context.Add(branch);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        // GET: Branches/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches.SingleOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }
            return View(branch);
        }

        // POST: Branches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Address,OpenHours,Latitude,Longitude")] Branch branch)
        {
            if (id != branch.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(branch);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BranchExists(branch.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        // GET: Branches/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .SingleOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        // POST: Branches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var branch = await _context.Branches.SingleOrDefaultAsync(m => m.Id == id);
            _context.Branches.Remove(branch);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool BranchExists(long id)
        {
            return _context.Branches.Any(e => e.Id == id);
        }
    }
}

SuperShraga/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SuperShraga.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SuperShraga.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Search()
        {
            OrderSearchViewModel vm = new OrderSearchViewModel();
            vm.OrderDateMax = DateTime.Today;
            vm.OrderDateMin = DateTime.Today.AddYears(-10);
            vm.TotalMin = 0;
            
            return View(vm);
        }

        [HttpPost]
        public IActionResult Search(OrderSearchViewModel vm)
        {
            List<OrderSearchViewResultModel> result = new List<OrderSearchViewResultModel>();

            if(ModelState.IsValid)
            {
                result = (from o in _context.Orders
                          where o.City.ToLower() == vm.City.ToLower()
                          && o.Country.ToLower() == vm.Country.ToLower()
                          && o.Total >= vm.TotalMin
                          && o.OrderDate.Date >= vm.OrderDateMin.Date
                          && o.OrderDate.Date <= vm.OrderDateMax.Date
                          select new OrderSearchViewResultModel
                          {
                              OrderDate = o.OrderDate,
                              Address = o.Address,
                              City = o.City,
                              Country = o.Country,
                              Email = o.Email,
                              FirstName = o.FirstName,
                              LastName = o.LastName,
                              Total = o.Total
                          }).ToList();
            }

            return View("Result", result);
        }

    }
}

SuperShraga/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuperShraga.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SuperShraga.Controllers
{
    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StoreController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var categories = _context.Categories.ToList();
            var anyCategory = _context.Categories.SingleOrDefault(m => m.CategoryId == 4);
            categories.Remove(anyCategory);
            return View(categories);
        }

        public IActionResult Browse(int id)
        {
            var categoryModel = _context.Categories.Include("Items").SingleOrDefault(m => m.CategoryId == id);
            
            if (categoryModel == null)
            {
                return NotFound();
            }

            return View(categoryModel);
        }

        [HttpGet]
        public IActionResult Search(string searchTerm)
        {
            List<Item> itemslist = new List<Item>();
            var items = _context.Items;

            foreach (Item i in items)
            {
                if(i.Name.ToLower().Contains(searchTerm.ToLower()))
                    itemslist.Add(i);
            }

            return View(itemslist);
        }

        [HttpGet]
        public IActionResult AdvancedSearch()
        {
            ViewBag.CategoryId = new SelectList(_context.Categories, "CategoryId", "Name", 4);
            ItemSearchViewModel vm = new ItemSearchViewModel();

            return View(vm);
        }

        [HttpPost]
        public IActionResult AdvancedSearch(ItemSearchViewModel vm)
        {
            List<Item> result = new List<Item>();
            ModelState.Remove("Price");
            ModelState.Remove("Name");

            if (vm.SearchName == null)
                vm.SearchName = string.Empty;

            if (ModelState.IsValid)
            {
                result = (from i in _context.Items
                          where i.Name.ToLower().Contains(vm.SearchName.ToLower())
                          && (vm.CategoryId == 4 || i.CategoryId == vm.CategoryId)
                          && i.Price <= vm.PriceMax && i.Price >= vm.PriceMin
                          select i).ToList();
            }

            return View("AdvancedSearchResult", result);
        }

        public async Task<IActionResult> Details(int id)
        {
            var item = await _context.Items.Include("Category").SingleOrDefaultAsync(m => m.Id == id);

            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }
    }
}

SuperShraga/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<SuperShraga.Models.Identity.ApplicationUser> SignInManager
@inject UserManager<SuperShraga.Models.Identity.ApplicationUser> UserManager


<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <title>SuperShraga - @ViewBag.Title</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("HeadScripts", false)

</head> 
<body>
    <div style="display: flex; flex-direction: column; height: 100%;">
        <nav class="navbar navbar-inverse centered-row" style="padding: 5px;">
            <div class="logo centered-row">
                <img href="@Url.Action("Index", "Home")" src="~/images/supershraga.png" style="width:40px; height:40px; margin: 0 10px;" />
                <a class="navbar-brand" style="float: none;" href="@Url.Action("Index", "Home")">SuperShraga</a>
            </div>
            <div style="width: 100%; display: flex; justify-content: space-between">
                <div class="nav-buttons">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index", "Store")">Store</a></li>
                        <li><a href="@Url.Action("Index", "Branches")">Branches</a></li>

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li><a href="@Url.Action("Index", "StoreManager")">Manage Store</a></li>
                            <li><a href="@Url.Action("UserManagement", "StoreManager")">Manage Users</a></li>
                            <li><a href="@Url.Action("Index", "Insights")">Business Insights</a></li>
                            <li><a href="@Url.Action("Search", "Order")">Orders Search</a></li>


                            <li><a href="@Url.Action("Logout", "Account")">Logout</a></li>

                        }
                        else if ((SignInManager.IsSignedIn(User) && User.IsInRole("Member")))
                        {
                            <li><a href="@Url.Action("Logout", "Account")">Logout</a></li>
                        }
                        else
                        {
                            <li><a href="@Url.Action("Login", "Account")">Login</a></li>
                            <li><a href="@Url.Action("Register", "Account")">Sign Up</a></li>
                        }
                    </ul>
                </div>
                <div class="navbar__middle-section">
                    <div style="height: 20px; align-self: center; overflow-y: hidden;">
                        <canvas id="clock"></canvas>
                    </div>
                    <div class="search">
                        <form action="@Url.Action("Search", "Store")">
                            <span class="centered-row">
                                <input id="search" type="text" class="searchInput" name="searchTerm" required="required" placeholder="Search..." autocomplete="off">
                                <button id="searchButton" class="icon" type="submit" style="height: 26.2px;"></button>
                            </span>
                        </form>
                        <a href="@Url.Action("AdvancedSearch", "Store")" style="color: #9d9d9d;">Advanced Search</a>
                    </div>
                </div>
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="navbar__right-section">
                    
                    <a href="@Url.Action("Index", "UserProfile")" style="color: #9d9d9d;">@UserManager.GetEmailAsync(UserManager.GetUserAsync(User).Result).Result</a>
                    <a href="@Url.Action("Index", "ShoppingCart")"><img src="~/images/cart.png" style="height: 40px;" /></a>
             
                </div>
            }
            </div>
        </nav>

        <div class="content">
            <segment class="container" style="width:100%; padding-top:30px;">
                @RenderBody()
            </segment>
            <aside>
                <a class="twitter-timeline" href="https://twitter.com/shraga19?ref_src=twsrc%5Etfw">Tweets by SuperShraga</a>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </aside>
            <footer style="text-align: center;">
                This site and all of it's content is the property of BenShai&trade;, Offek Marelly and Yarin Maguleanu. All rights reserved 2018-2018 &copy;
            </footer>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script name="clock script">
        var canvas = $("#clock");
        var c = canvas[0].getContext('2d');

        function drawClock() {
            // clear the background
            c.fillStyle = '#222';
            //c.fillRect(0, 0, canvas.width(), canvas.height());
            c.fillRect(0, 0, 1000, 1000);

            // Get the current time
            var now = new Date(),
                h = now.getHours(),
                m = now.getMinutes(),
                s = now.getSeconds();

            // Make values like '5' into '05'
            h = addLeadingZeroWhenNecessary(h);
            m = addLeadingZeroWhenNecessary(m);
            s = addLeadingZeroWhenNecessary(s);

            // Assemble the text
            var clockText = h + ':' + m + ':' + s,
                x = 10,
                y = 50;

            // This green color was picked
            // using http://jscolor.com/
            c.fillStyle = '#9d9d9d';

            // Draw the text
            c.font = '50pt Arial';
            c.strokeStyle = '#9d9d9d';
            c.fillText(clockText, x, y);
            c.strokeText(clockText, x, y);
        }

        function addLeadingZeroWhenNecessary(s) {
            return (s < 10 ? '0' : '') + s;
        }

        // Draw the clock right away
        drawClock();

        // Then draw the clock every subsequent second
        setInterval(drawClock, 1000);
    </script>

    <script>
        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        (async () => {
            await sleep(200);

            for (let elm of $('.cool-fade')) {
                elm.style.opacity = 1;
                elm.style.transform = 'scale(1, 1)';
                await sleep(100);
            }
        })();
    </script>

    @RenderSection("Scripts", false)

</body>
</html>